---

- name: Ensure zsh is installed
  apt:
    name: zsh
    state: present

- name: Install Powerlevel10k
  become_user: kali
  git: 
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{lookup('env', 'HOME')}}/powerlevel10k"
    depth: 1

- name: PowerLevel10k is enabled in .zshrc
  become_user: kali
  lineinfile:
    path: "{{lookup('env', 'HOME')}}/.zshrc"
    line: source ~/powerlevel10k/powerlevel10k.zsh-theme

...