---

- name: Install gnome-terminal
  apt:
    name: gnome-terminal
    state: present

- name: Change terminal emulator
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/gnome-terminal

- name: Install Regolith repository
  ansible.builtin.apt_repository:
    repo: ppa:regolith-linux/release
    codename: focal

- name: Install Regolith Desktop (Standard)
  ansible.builtin.package:
    name: regolith-desktop-standard
    state: present

- name: Ensure regolith config directory exists
  become_user: kali
  ansible.builtin.file:
    path: "{{lookup('env', 'HOME')}}/.config/regolith"
    state: directory

- name: Override Regolith font configuration
  become_user: kali
  copy:
    src: ../files/Xresources
    dest: "{{lookup('env', 'HOME')}}/.config/regolith/Xresources"

...