---

- name: Install Regolith repository
  ansible.builtin.apt_repository:
    repo: ppa:regolith-linux/release
    codename: focal

- name: Install Regolith Desktop (Standard)
  ansible.builtin.package:
    name: regolith-desktop-standard
    state: present

...