---

- name: Ensure vim is not installed
  package:
    name: vim
    state: absent

- name: Ensure vim related packages are not installed
  package:
    name: vim-*
    state: absent

- name: Ensure Neovim is installed
  package:
    name: neovim
    state: present

- name: Ensure vim autoload directory exists
  become_user: kali
  ansible.builtin.file:
    path: "{{lookup('env', 'HOME')}}/.local/share/nvim/site/autoload"
    state: directory

- name: Install vim-plug
  become_user: kali
  get_url: 
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{lookup('env', 'HOME')}}/.local/share/nvim/site/autoload"

- name: Ensure vim config directory exists
  become_user: kali
  ansible.builtin.file:
    path: "{{lookup('env', 'HOME')}}/.config/nvim"
    state: directory

- name: Ensure init.vim exists at config location
  become_user: kali
  copy:
    src: ../files/init.vim
    dest: "{{lookup('env', 'HOME')}}/.config/nvim"

- name: Ensure plugins are up to date
  become_user: kali
  shell: vim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty

...